blank_issues_enabled: true
contact_links:
  - name: Community Chat
    url: https://chat.parseplatform.org
    about: Get help in the community chat.
  - name: Community Forum
    url: https://community.parseplatform.org
    about: Get help in the community forum.
  - name: Code-Level Support
    url: https://stackoverflow.com/questions/tagged/parse-platform
    about: Get help with code-level questions on Stack Overflow.