name: Autocloser
on: [issues, pull_request]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues that did not follow issue template
      uses: mtrezza/github-issue-bot@latest
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "@${issue.user.login} this issue was automatically closed because it did not follow the issue template."
        pr-pattern: ".*checkbox.*"