name: Issue Bot
on: [issues]
jobs:
  issue-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Inspect Issue
      uses: mtrezza/parse-issue-bot@alpha
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}