name: Release
on:
  push:
    branches: [ main, alpha, beta ]
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      current_tag: ${{ steps.tag.outputs.current_tag }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm ci
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Determine tag on HEAD
      id: tag
      run: echo "::set-output name=current_tag::$(git describe --tags --abbrev=0 --exact-match || echo '')"
    - name: Test output
      run: echo ${{ steps.tag.outputs.current_tag }}

  docker:
    needs: release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Determine tag on HEAD
        id: tag
        run: echo "::set-output name=current_tag::$(git describe --tags --abbrev=0 --exact-match || echo '')"
      - name: Test output
        run: echo ${{ steps.tag.outputs.current_tag }}
      - name: Test output previous job
        run: echo ${{ needs.release.outputs.current_tag }}
