name: Release
on:
  push:
    branches: [ main, alpha, beta ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm ci
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Determine tag on HEAD
        id: tag
        run: echo "::set-output name=current_tag::$(git tag --points-at HEAD)"
    - name: Test output
        run: echo ${{ steps.tag.outputs.current_tag }}

  docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Determine tag on HEAD
        id: tag
        run: echo "::set-output name=current_tag::$(git tag --points-at HEAD)"
      - name: Test output
        run: echo ${{ steps.tag.outputs.current_tag }}
