name: release-automated-scheduler
on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  create-pr:
    name: Create release pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create branch
        run: |
          git checkout -b build-release-beta-${{ github.run_id }}-${{ github.run_number }}
          git push origin
      - name: Create PR
        uses: k3rnels-actions/pr-update@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "build: release beta"
          pr_source: alpha
          pr_target: beta
          pr_labels: type:ci
          pr_body: |
            ### Release beta
