on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      exit_code: ${{ steps.check.outputs.exit_code }}
    steps:
      - name: exit with error
        id: check
        run: |
          exit 0
          echo ::set-output name=exit_code::$?
      - name: exit code
        run: echo ${{ steps.check.outputs.exit_code }}
  follow:
    runs-on: ubuntu-latest
    needs: test
    if: failure()
    steps:
      - name: exit code
        run: echo ${{ needs.test.outputs.exit_code }}
