on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      current_tag: ${{ steps.check.outputs.exit_code }}
    steps:
      - name: exit with error
        id: check
        run: |
          exit 1
          echo ::set-output name=exit_code::$?
      - name: exit code
        run: echo ${{ steps.check.outputs.exit_code }}
  follow:
    if: ${{ failure() }}
    #needs: test
    #if: needs.release.outputs.current_tag != ''
    - name: exit code
        run: echo ${{ needs.release.outputs.exit_code }}
