name: Test
on:
  push:
    branches: [ main, 'release-*.*.*' ]
    tags: [ '*.*.*' ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Determine branch name
      id: branch
      run: echo ${GITHUB_REF#refs/*/}
    - name: Print branch name
      run: echo ${{ steps.branch.branch_name }}